### ISSUE TITLE
Hi, my friend. 

### ISSUE THREAD

**Issue by alireza777** [Hackerscolonyofficial/HCO-Phisher#1]
I'm new, I'll ask you for help and answer my questions if possible.  
1.Is Thermox 10 for Android??
2.You win account hacking on other sites there is a tool for thermox

**Comment by Hackerscolonyofficial** [comment]
Yes we can run Termux in Android 10

**Comment by alireza777** [comment]
But I read yesterday on another page that for Android 10 is not your new version, i.e. the device must be rooted

**Comment by alireza777** [comment]
دوست من کدوم ورژن رو باید دانلود کنم ؟

**Comment by alireza777** [comment]
From fdroid I tried to download but not installed

**Comment by Hackerscolonyofficial** [comment]
Join our group👇

https://chat.whatsapp.com/HtMWWmyi7QQ0sMV7tm4FYX

**Comment by alireza777** [comment]
hi dear friend how are you?
